services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=dev_username
      - DB_PASSWORD=dev_password
      - DB_NAME=parking
    depends_on:
      - db
    
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'  
      MYSQL_DATABASE: 'parking'             
      MYSQL_USER: 'dev_username'           
      MYSQL_PASSWORD: 'dev_password'       
    ports:
     - "3406:3306"